### ISSUE TITLE
[BUG] Выдача саморепутации каналом 

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [mirea-ninja/ninja-telegram-bot#4]
**Описание ошибки**
Возможность выдачи каналом репутации пользовательскому профилю (и наоборот пользователь дает каналу) под одной учетной записью.

**Шаги воспроизведения**
1. Написать сообщение в группе от имени пользователя
2. Выдать +реп своему сообщению от имени канала

**Comment by 0niel** [comment]
Fixed!
